---

default: &default
  socket_ip: 127.0.0.1
  socket_port: 21314
  logic_ip: 127.0.0.1
  logic_port: 56789

  transports:
    - polling
    - websocket #服务器端尽量开启websocket, 当有大量客户端断开时,如果客户端与服务器通过websocket连接的话,可以保证服务器回调函数能可靠的调用(不存在回调不执行的情况)
  pingInterval: 20000
  pingTimeout: 10000


  redis_address: '127.0.0.1:6379'
#    - 127.0.0.1:10010
#    - 127.0.0.1:10020
  redis_prefix: ipush_
  redis_push_msg_id_prefix: p_msg_id_                                    #消息id的前缀
  redis_client_set_prefix: client_set_                                   #保存每个命名空间下的客户端集合
  redis_user_set_prefix: user_set_                                       #保存每个命名空间下的用户集合
  redis_room_set_prefix: room_set_                                       #保存每个命名空间下的房间集合(只保存普通房间,不包括用户类型的房间)
  redis_user_room_set_prefix: user_room_set_                             #保存单个用户下的房间集合
  redis_room_user_set_prefix: room_user_set_                             #保存单个房间下的用户集合
  redis_push_message_list_prefix: push_message_list_                     #保存每个命名空间下推送消息的id数组(根据push_message_list_max_limit保存有限的id)
  redis_push_message_temp_list_prefix: push_message_temp_list_           #临时保存所有命名空间下推送的消息id列表,post_worker会通过redis的消息队列把对于的消息取出来进行处理
  redis_push_ack_set_prefix: push_ack_set_                               #保存推送确认报告的设备ID集合
  redis_push_msg_uuid: push_msg_uuid_int                                 #保存消息自增id
  redis_client_hash_prefix: client_hash_                                 #保存单个客户端的信息
  redis_android_unread_message_list: android_unread_message_list_        #保存每一个android设备未读的消息列表,

  redis_namespace_key_z: nsp_z_                                          #保存命名空间的列表
  #命名空间下配置项: key,name,apns_topic,apns_host,apns_port,apns_expiration,connect_callback,disconnect_callback,auth_passwd,callback_auth
  redis_namespace_set_prefix: nsp_set_                                   #保存单个命名空间下的配置信息

#这些键需要使用hash tag 保证集群环境下可以落到单一实例上,写代码的时候需要格外注意
  redis_room_client_set_prefix: room_client_set_                                   #保存单个房间下在线的客户端集合(包括普通房间和用户类型的房间)
  redis_total_room_client_set_prefix: total_room_client_set_                       #保存单个房间下所有客户端集合(包括普通房间和用户类型的房间)
  redis_ios_room_client_set_prefix: ios_room_client_set_                           #保存单个房间下在线的ios客户端集合(包括普通房间和用户类型的房间)
  redis_total_ios_room_client_set_prefix: total_ios_room_client_set_               #保存单个房间下所有ios客户端集合(包括普通房间和用户类型的房间)
  redis_total_android_room_client_set_prefix: total_android_room_client_set_       #保存单个房间下所有android客户端集合(包括普通房间和用户类型的房间)
  redis_android_room_client_set_prefix: android_room_client_set_                   #保存单个房间下在线的android客户端集合(包括普通房间和用户类型的房间)
#  redis_post_message_android_set_prefix: push_msg_android_set_                     #保存需要对推送消息进行后续处理的android设备列表
#  redis_post_message_ios_set_prefix: push_msg_ios_set_                             #保存需要对推送消息进行后续处理的ios设备列表

  redis_room_transfer_channel: room_transfer
  redis_home_broadcast_channel: home_broadcast

  room_activity_broadcast: true
  worker_message_timeout: 5000
#  ack_enable: true
  client_push: true
#  client_report_online: true
#  client_report_push: true
#  client_transfer: true

  push_message_h_expire: 120000000                                         #以秒为单位
  push_message_list_max_limit: 5000000
  user_room_prefix: user_                                                  #用户类型的房间名前缀
  room_prefix: room_                                                       #房间名前缀
  report_online_list_max_limit: 1000
  report_push_ack_detail_max_limit: 1000
  android_unread_message_list_max_limit: 100                               #每一个android设备可以保存未读消息总数

  log_watch_change: false  #是否启动实时日志刷新

  emit_msg_pick_key: true  #在线推送到消息中是否过滤不必要的字段

  apns_dev_server: 'https://api.development.push.apple.com:443'
  apns_production_server: 'https://api.push.apple.com:443'
  apns_aps_alert: '通知'
  apns_payload_size: 4000

  admin_name: liuss
  admin_passwd: 123456

  log_path:

dev:
  << : *default

  transports:
    - websocket

  client_transfer: false
